const mockData = {
  updatedAt: '2026/08/20 14:30',
  cities: [
    ['臺北市',32,40,'多雲時晴','normal','normal'],['新北市',31,50,'短暫雨','normal','normal'],['基隆市',29,70,'局部短暫雨','warning','normal'],['桃園市',32,30,'多雲','normal','normal'],['新竹市',31,30,'多雲','normal','normal'],['新竹縣',30,40,'多雲','normal','normal'],['苗栗縣',31,40,'多雲','normal','normal'],['臺中市',33,20,'晴時多雲','normal','normal'],['彰化縣',33,20,'晴時多雲','normal','normal'],['南投縣',32,30,'多雲','normal','normal'],['雲林縣',33,20,'晴時多雲','normal','normal'],['嘉義市',34,20,'晴時多雲','normal','normal'],['嘉義縣',34,30,'晴時多雲','normal','normal'],['臺南市',35,20,'晴時多雲','normal','normal'],['高雄市',35,20,'晴時多雲','normal','normal'],['屏東縣',35,30,'晴時多雲','normal','normal'],['宜蘭縣',29,80,'有雨','warning','normal'],['花蓮縣',30,60,'短暫雨','warning','normal'],['臺東縣',32,30,'多雲','normal','normal'],['澎湖縣',31,20,'晴時多雲','normal','normal'],['金門縣',30,20,'晴時多雲','normal','normal'],['連江縣',28,50,'多雲','normal','normal']
  ].map(([name,temp,rain,condition,alert,work])=>({name,temp,rain,condition,alert,work,school:work})),
  alerts: [{level:'橙色', title:'大雨特報', cities:'基隆市、宜蘭縣、花蓮縣', time:'2026/08/20 13:45', source:'中央氣象署', tone:'orange'}, {level:'黃色', title:'高溫資訊', cities:'臺中市以南地區', time:'2026/08/20 12:00', source:'中央氣象署', tone:'yellow'}],
  closures: [['臺北市','正常','正常','—','臺北市政府'],['新北市','正常','正常','—','新北市政府'],['基隆市','未公告','未公告','—','基隆市政府'],['宜蘭縣','正常','正常','2026/08/20 08:10','宜蘭縣政府'],['花蓮縣','正常','正常','2026/08/20 08:05','花蓮縣政府'],['臺東縣','正常','正常','2026/08/20 08:00','臺東縣政府'],['臺中市','正常','正常','—','臺中市政府'],['高雄市','正常','正常','—','高雄市政府']].map(([city,work,school,time,source])=>({city,work,school,time,source})),
  history: [{type:'大雨特報',area:'宜蘭縣、花蓮縣',time:'今天 13:45',status:'已讀',tone:'orange'},{type:'高溫資訊',area:'臺中市以南',time:'今天 12:00',status:'已讀',tone:'yellow'},{type:'停班停課公告',area:'基隆市',time:'昨天 18:20',status:'已讀',tone:'gray'}]
};

const state = { view: 'overview', city: '臺北市', subscribed: true };
const el = (id) => document.getElementById(id);
const statusLabel = (value) => `<span class="status status-${value === '正常' ? 'normal' : value === '停班停課' ? 'closed' : 'pending'}"><span class="status-dot"></span>${value}</span>`;
function weatherIcon(city){ return city.condition.includes('雨') ? '☂' : '☀'; }
function renderWeatherCard(city){ return `<button class="weather-card" data-city="${city.name}" type="button"><div class="card-top"><span class="city-name">${city.name}</span><span class="alert-mini ${city.alert === 'warning' ? 'is-warning' : ''}">${city.alert === 'warning' ? '有警特報' : '無警特報'}</span></div><div class="weather-main"><span class="weather-icon" aria-hidden="true">${weatherIcon(city)}</span><strong>${city.temp}°</strong><div><p>${city.condition}</p><small>降雨機率 ${city.rain}%</small></div></div><div class="city-status"><span>上班 ${statusLabel(city.work)}</span><span>上課 ${statusLabel(city.school)}</span></div></button>`; }
function renderOverview(){ return `<section class="page-heading"><div><p class="eyebrow">OVERVIEW / 全台即時狀態</p><h2>全台總覽</h2><p class="subheading">掌握各縣市天氣、警特報與停班停課公告。</p></div><div class="data-source"><span class="source-icon">✓</span><div><strong>資料已同步</strong><small>中央氣象署 · 各縣市政府</small></div></div></section><section class="summary-grid"><article class="summary-card"><span>全台縣市</span><strong>22</strong><small>個縣市</small></article><article class="summary-card summary-alert"><span>目前警特報</span><strong>${mockData.alerts.length}</strong><small>件生效中</small></article><article class="summary-card"><span>停班停課</span><strong>0</strong><small>個縣市</small></article><article class="summary-card"><span>未公告</span><strong>${mockData.closures.filter(x=>x.work==='未公告').length}</strong><small>個縣市</small></article></section><div class="section-heading"><div><p class="eyebrow">WEATHER CONDITIONS</p><h3>各縣市天氣</h3></div><span class="section-note">點選縣市查看詳細資訊</span></div><section class="weather-grid">${mockData.cities.map(renderWeatherCard).join('')}</section><div class="content-grid"><section class="panel"><div class="panel-heading"><div><p class="eyebrow">ACTIVE ALERTS</p><h3>天氣警特報</h3></div><span class="count-badge">${mockData.alerts.length} 件</span></div><div class="alert-list">${mockData.alerts.map(renderAlert).join('')}</div></section><section class="panel closure-panel"><div class="panel-heading"><div><p class="eyebrow">OFFICE & SCHOOL STATUS</p><h3>停班停課摘要</h3></div><button class="text-button" data-view="detail">查看完整表格 →</button></div><div class="mini-table">${mockData.closures.slice(0,5).map(x=>`<div class="mini-row"><strong>${x.city}</strong><span>${statusLabel(x.work)}</span><span>${statusLabel(x.school)}</span></div>`).join('')}</div></section></div>`; }
function renderAlert(a){ return `<article class="alert-item alert-${a.tone}"><span class="alert-symbol">!</span><div><div class="alert-title"><strong>${a.title}</strong><span class="level-tag">${a.level}警戒</span></div><p>影響範圍：${a.cities}</p><small>發布 ${a.time} · ${a.source}</small></div></article>`; }
function renderDetail(){ const city=mockData.cities.find(x=>x.name===state.city)||mockData.cities[0]; return `<section class="page-heading"><div><button class="back-link" data-view="overview">← 返回全台總覽</button><p class="eyebrow">CITY DETAIL / ${city.name}</p><h2>${city.name} 詳情</h2><p class="subheading">目前天氣與行政公告資訊。</p></div><label class="select-wrap">選擇縣市<select id="detailCitySelect">${mockData.cities.map(x=>`<option ${x.name===city.name?'selected':''}>${x.name}</option>`).join('')}</select></label></section><section class="detail-hero panel"><div><p class="eyebrow">CURRENT WEATHER</p><span class="weather-icon large">${weatherIcon(city)}</span><strong class="detail-temp">${city.temp}°</strong><h3>${city.condition}</h3><p>降雨機率 ${city.rain}% · 今天 14:30</p></div><div class="detail-metrics"><div><span>上班狀態</span>${statusLabel(city.work)}</div><div><span>上課狀態</span>${statusLabel(city.school)}</div><div><span>警特報</span>${city.alert==='warning'?'<span class="status status-alert">有警特報</span>':'<span class="status status-normal">目前無</span>'}</div></div></section><div class="content-grid"><section class="panel"><div class="panel-heading"><div><p class="eyebrow">LOCAL ALERT</p><h3>相關警特報</h3></div></div>${mockData.alerts.filter(a=>a.cities.includes(city.name)||city.alert==='warning').map(renderAlert).join('')||'<div class="empty-state">目前沒有影響本縣市的警特報</div>'}</section><section class="panel"><div class="panel-heading"><div><p class="eyebrow">FORECAST</p><h3>未來 6 小時</h3></div></div><div class="forecast-row">${['15:00','16:00','17:00','18:00','19:00','20:00'].map((time,i)=>`<div><small>${time}</small><span>${i<3?'☀':'☂'}</span><strong>${city.temp-i}°</strong><small>${Math.max(20,city.rain-i*5)}%</small></div>`).join('')}</div></section></div>`; }
function renderClosureTable(){ return `<section class="page-heading"><div><p class="eyebrow">OFFICE & SCHOOL STATUS</p><h2>停班停課公告</h2><p class="subheading">各縣市最新上班上課狀態與公告來源。</p></div><div class="legend"><span>${statusLabel('正常')} 正常</span><span>${statusLabel('未公告')} 未公告</span><span>${statusLabel('停班停課')} 停班停課</span></div></section><section class="panel table-panel"><div class="table-toolbar"><strong>全台縣市公告</strong><span>最後同步：${mockData.updatedAt}</span></div><div class="table-scroll"><table><thead><tr><th>縣市</th><th>上班狀態</th><th>上課狀態</th><th>公告時間</th><th>資料來源</th></tr></thead><tbody>${mockData.closures.map(x=>`<tr><th>${x.city}</th><td>${statusLabel(x.work)}</td><td>${statusLabel(x.school)}</td><td>${x.time}</td><td>${x.source}</td></tr>`).join('')}</tbody></table></div></section>`; }
function renderSubscription(){ return `<section class="page-heading"><div><p class="eyebrow">SUBSCRIPTION / NOTIFICATIONS</p><h2>訂閱設定</h2><p class="subheading">選擇你關心的縣市與通知類型。</p></div></section><section class="panel subscription-panel"><div class="form-section"><h3>通知偏好</h3><p>目前設定會套用於所有裝置。</p><label class="toggle-row"><span><strong>啟用即時通知</strong><small>警特報與停班停課公告發布時通知</small></span><input id="subToggle" type="checkbox" ${state.subscribed?'checked':''} /><span class="toggle-ui"></span></label><fieldset><legend>通知類型</legend><label class="check-row"><input type="checkbox" checked /> <span>天氣警特報</span></label><label class="check-row"><input type="checkbox" checked /> <span>停班停課公告</span></label><label class="check-row"><input type="checkbox" /> <span>地震速報</span></label></fieldset></div><div class="form-section"><h3>關注縣市</h3><p>選擇要接收通知的縣市。</p><div class="city-check-grid">${mockData.cities.slice(0,12).map((c,i)=>`<label class="city-check"><input type="checkbox" ${i<3?'checked':''} /><span>${c.name}</span></label>`).join('')}</div><button class="button button-primary" id="saveSubscription" type="button">儲存設定</button></div></section>`; }
function renderHistory(){ return `<section class="page-heading"><div><p class="eyebrow">NOTIFICATION HISTORY</p><h2>通知歷史</h2><p class="subheading">查看近期推播與系統通知紀錄。</p></div><button class="button button-secondary" type="button">匯出紀錄</button></section><section class="panel table-panel"><div class="table-toolbar"><strong>近期通知</strong><span>共 ${mockData.history.length} 筆</span></div><div class="table-scroll"><table><thead><tr><th>通知類型</th><th>影響範圍</th><th>發送時間</th><th>狀態</th></tr></thead><tbody>${mockData.history.map(x=>`<tr><th><span class="history-type history-${x.tone}"></span>${x.type}</th><td>${x.area}</td><td>${x.time}</td><td>${x.status}</td></tr>`).join('')}</tbody></table></div></section>`; }
function render(){ const views={overview:renderOverview,detail:renderDetail,subscription:renderSubscription,history:renderHistory}; el('appMain').innerHTML=views[state.view](); document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('is-active',x.dataset.view===state.view)); bind(); }
function bind(){ document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>{state.view=x.dataset.view; render(); window.scrollTo({top:0,behavior:'smooth'});})); document.querySelectorAll('[data-city]').forEach(x=>x.addEventListener('click',()=>{state.city=x.dataset.city;state.view='detail';render();window.scrollTo({top:0,behavior:'smooth'});})); const select=el('detailCitySelect'); if(select) select.addEventListener('change',e=>{state.city=e.target.value;render();}); const toggle=el('subToggle'); if(toggle) toggle.addEventListener('change',e=>state.subscribed=e.target.checked); const save=el('saveSubscription'); if(save) save.addEventListener('click',()=>showToast('訂閱設定已儲存')); }
function showToast(message){ const toast=el('toast');toast.textContent=message;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),2200); }
el('refreshBtn').addEventListener('click',()=>{el('lastUpdated').textContent='更新於 '+new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'});showToast('資料已更新');});
el('lastUpdated').textContent='更新於 '+mockData.updatedAt.split(' ')[1];
render();
// API boundary: replace these mock providers with fetch calls when backend is ready.
const weatherDataProvider=async()=>mockData.cities; const alertDataProvider=async()=>mockData.alerts; const closureDataProvider=async()=>mockData.closures;
void weatherDataProvider; void alertDataProvider; void closureDataProvider;
